# Azure DevOps Pipeline for REBC Infrastructure

trigger: none

parameters:
  - name: environment
    displayName: 'Environment'
    type: string
    default: dev1
    values:
      - dev1
      - sit
      - uat
      - prod

  - name: confirmDeploy
    displayName: 'Confirm deployment (must be true to deploy)'
    type: boolean
    default: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'ado-sb'

steps:
  - script: az bicep build --file main.bicep
    workingDirectory: 'library'
    displayName: 'Validate Bicep'

  - task: AzureCLI@2
    displayName: 'Deploy Infrastructure (${{ parameters.environment }})'
    condition: and(succeeded(), eq('${{ parameters.confirmDeploy }}', 'true'))
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: 'bash'
      scriptLocation: 'scriptPath'
      scriptPath: 'library/deploy.sh'
      arguments: '${{ parameters.environment }} --confirm'
