# Azure DevOps Build Pipeline for REBC Infrastructure
# Validates Bicep templates and publishes artifacts for Azure DevOps Releases

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - library/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'ado-bcsit'

steps:
  - checkout: self

  - script: |
      az bicep version
      az bicep build --file main.bicep
    workingDirectory: 'library'
    displayName: 'Validate Bicep Templates'

  - task: AzureCLI@2
    displayName: 'Azure Deployment What-If (Dev)'
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      workingDirectory: '$(System.DefaultWorkingDirectory)/library'
      inlineScript: |
        az deployment sub what-if \
          --location australiaeast \
          --template-file main.bicep \
          --parameters environment=dev

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Bicep Library Artifact'
    inputs:
      PathtoPublish: 'library'
      ArtifactName: 'bicep-library'
      publishLocation: 'Container'
