# Azure DevOps Pipeline for REBC Infrastructure

trigger: none

parameters:
  - name: environment
    displayName: 'Environment'
    type: string
    default: dev1
    values:
      - dev1
      - sit
      - uat
      - prod

  - name: whatIf
    displayName: 'What-If (preview changes only)'
    type: boolean
    default: false

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'ado-sb'

steps:
  - script: az bicep build --file main.bicep
    workingDirectory: 'library'
    displayName: 'Validate Bicep'

  - ${{ if eq(parameters.whatIf, true) }}:
    - task: AzureCLI@2
      displayName: 'What-If Infrastructure (${{ parameters.environment }})'
      inputs:
        azureSubscription: ${{ variables.azureServiceConnection }}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub what-if \
            --location australiaeast \
            --template-file library/main.bicep \
            --parameters environment=${{ parameters.environment }} \
            --name deploy-bcrev-${{ parameters.environment }}

  - ${{ if eq(parameters.whatIf, false) }}:
    - task: AzureCLI@2
      displayName: 'Deploy Infrastructure (${{ parameters.environment }})'
      inputs:
        azureSubscription: ${{ variables.azureServiceConnection }}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create \
            --location australiaeast \
            --template-file library/main.bicep \
            --parameters environment=${{ parameters.environment }} \
            --name deploy-bcrev-${{ parameters.environment }}
