# Azure DevOps Pipeline for REBC Infrastructure
# Validates Bicep templates and deploys to the selected environment

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - library/**

parameters:
  - name: environment
    displayName: 'Environment'
    type: string
    default: dev
    values:
      - dev
      - uat
      - prod

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'ado-bcsit'

stages:
  - stage: Build
    displayName: 'Build & Validate'
    jobs:
      - job: Validate
        steps:
          - script: |
              az bicep version
              az bicep build --file main.bicep
            workingDirectory: 'library'
            displayName: 'Validate Bicep Templates'

          - task: AzureCLI@2
            displayName: 'Validate Deployment (${{ parameters.environment }})'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment sub validate \
                  --location australiaeast \
                  --template-file library/main.bicep \
                  --parameters environment=${{ parameters.environment }}

          - task: AzureCLI@2
            displayName: 'Preview Changes (What-If)'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment sub what-if \
                  --location australiaeast \
                  --template-file library/main.bicep \
                  --parameters environment=${{ parameters.environment }}

  - stage: Deploy
    displayName: 'Deploy to ${{ parameters.environment }}'
    dependsOn: Build
    jobs:
      - deployment: Deploy
        environment: '${{ parameters.environment }}'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureCLI@2
                  displayName: 'Deploy Infrastructure (${{ parameters.environment }})'
                  inputs:
                    azureSubscription: $(azureServiceConnection)
                    scriptType: 'bash'
                    scriptLocation: 'scriptPath'
                    scriptPath: 'library/deploy.sh'
                    arguments: '${{ parameters.environment }}'
