# Azure DevOps Pipeline for REBC Infrastructure

trigger: none

parameters:
  - name: environment
    displayName: 'Environment'
    type: string
    default: dev
    values:
      - dev
      - uat
      - prod

  - name: deployResourceGroup
    displayName: 'Deploy Resource Group'
    type: boolean
    default: false

  - name: deployManagedIdentity
    displayName: 'Deploy Managed Identity'
    type: boolean
    default: false

  - name: deployLogAnalyticsWorkspace
    displayName: 'Deploy Log Analytics Workspace'
    type: boolean
    default: false

  - name: deployContainerRegistry
    displayName: 'Deploy Container Registry'
    type: boolean
    default: false

  - name: deployContainerAppsEnvironment
    displayName: 'Deploy Container Apps Environment'
    type: boolean
    default: false

  - name: deployContainerAppJobBill
    displayName: 'Deploy Container App Job - Bill'
    type: boolean
    default: false

  - name: deployContainerAppJobData
    displayName: 'Deploy Container App Job - Data'
    type: boolean
    default: false

  - name: deploySqlServer
    displayName: 'Deploy SQL Server'
    type: boolean
    default: false

  - name: deploySqlDatabase
    displayName: 'Deploy SQL Database'
    type: boolean
    default: false

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'ado-bcsit'

steps:
  - script: az bicep build --file main.bicep
    workingDirectory: 'library'
    displayName: 'Validate Bicep'

  - task: AzureCLI@2
    displayName: 'Deploy Infrastructure (${{ parameters.environment }})'
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: 'bash'
      scriptLocation: 'scriptPath'
      scriptPath: 'library/deploy.sh'
      arguments: >-
        ${{ parameters.environment }}
        ${{ parameters.deployResourceGroup }}
        ${{ parameters.deployManagedIdentity }}
        ${{ parameters.deployLogAnalyticsWorkspace }}
        ${{ parameters.deployContainerRegistry }}
        ${{ parameters.deployContainerAppsEnvironment }}
        ${{ parameters.deployContainerAppJobBill }}
        ${{ parameters.deployContainerAppJobData }}
        ${{ parameters.deploySqlServer }}
        ${{ parameters.deploySqlDatabase }}
