# Azure DevOps Build Pipeline for REBC Infrastructure
# Validates Bicep templates and publishes artifacts
# Deployment to Dev, UAT, and Prod is handled by Azure DevOps Release pipelines

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - library/**

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - script: |
      az bicep version
      az bicep build --file main.bicep
    workingDirectory: 'library'
    displayName: 'Validate Bicep Templates'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Bicep Library Artifact'
    inputs:
      PathtoPublish: 'library'
      ArtifactName: 'bicep-library'
      publishLocation: 'Container'
