# Azure DevOps Pipeline for REBC Infrastructure

trigger: none

parameters:
  - name: environment
    displayName: 'Environment'
    type: string
    default: dev1
    values:
      - dev1
      - sit
      - uat
      - prod
  - name: azureServiceConnection
    displayName: 'Azure Service Connection'
    type: string
    default: 'ado-sb'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: az bicep build --file main.bicep
    workingDirectory: 'library'
    displayName: 'Validate Bicep'

  - task: AzureCLI@2
    displayName: 'Deploy Infrastructure (${{ parameters.environment }})'
    inputs:
      azureSubscription: ${{ parameters.azureServiceConnection }}
      scriptType: 'bash'
      scriptLocation: 'scriptPath'
      scriptPath: 'library/deploy.sh'
      arguments: '${{ parameters.environment }} --confirm'
      addSpnToEnvironment: true
